// <auto-generated />
using System;
using IsoDocs.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IsoDocs.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IsoDocsDbContext))]
    [Migration("20260507130000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IsoDocs.Domain.Attachments.Attachment", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("BlobUrl").IsRequired().HasMaxLength(2048).HasColumnType("nvarchar(2048)");
                b.Property<Guid>("CaseId").HasColumnType("uniqueidentifier");
                b.Property<string>("ContentType").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<string>("FileName").IsRequired().HasMaxLength(512).HasColumnType("nvarchar(512)");
                b.Property<bool>("IsDeleted").HasColumnType("bit");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.Property<Guid>("UploadedByUserId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("CaseId");
                b.HasIndex("IsDeleted");
                b.HasIndex("UploadedByUserId");
                b.ToTable("Attachments", (string)null);
            });

            modelBuilder.Entity("IsoDocs.Domain.Audit.AuditTrail", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("Action").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                b.Property<string>("ChangesJson").HasColumnType("nvarchar(max)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<string>("EntityId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                b.Property<string>("EntityType").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                b.Property<string>("IpAddress").HasMaxLength(64).HasColumnType("nvarchar(64)");
                b.Property<string>("LastError").HasColumnType("nvarchar(max)");
                b.Property<DateTimeOffset>("OccurredAt").HasColumnType("datetimeoffset");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.Property<string>("UserAgent").HasMaxLength(512).HasColumnType("nvarchar(512)");
                b.Property<Guid?>("UserId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("EntityType", "EntityId");
                b.HasIndex("OccurredAt");
                b.HasIndex("UserId");
                b.ToTable("AuditTrails", (string)null);
            });

            modelBuilder.Entity("IsoDocs.Domain.Cases.Case", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("CaseNumber").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                b.Property<DateTimeOffset?>("ClosedAt").HasColumnType("datetimeoffset");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<Guid?>("CustomerId").HasColumnType("uniqueidentifier");
                b.Property<string>("CustomVersionNumber").HasMaxLength(64).HasColumnType("nvarchar(64)");
                b.Property<Guid>("DocumentTypeId").HasColumnType("uniqueidentifier");
                b.Property<DateTimeOffset?>("ExpectedCompletionAt").HasColumnType("datetimeoffset");
                b.Property<int>("FieldVersion").HasColumnType("int");
                b.Property<DateTimeOffset>("InitiatedAt").HasColumnType("datetimeoffset");
                b.Property<Guid>("InitiatedByUserId").HasColumnType("uniqueidentifier");
                b.Property<DateTimeOffset?>("OriginalExpectedAt").HasColumnType("datetimeoffset");
                b.Property<DateTime>("PeriodEnd").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodEndColumn", true);
                b.Property<DateTime>("PeriodStart").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodStartColumn", true);
                b.Property<int>("Status").HasColumnType("int");
                b.Property<int>("TemplateVersion").HasColumnType("int");
                b.Property<string>("Title").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.Property<DateTimeOffset?>("VoidedAt").HasColumnType("datetimeoffset");
                b.Property<Guid>("WorkflowTemplateId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("CaseNumber").IsUnique();
                b.HasIndex("CustomerId");
                b.HasIndex("DocumentTypeId");
                b.HasIndex("InitiatedByUserId");
                b.HasIndex("WorkflowTemplateId");
                b.HasIndex("Status", "InitiatedAt");
                b.ToTable("Cases", (string)null, tb =>
                {
                    tb.HasAnnotation("SqlServer:IsTemporal", true);
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableName", "CasesHistory");
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableSchema", null);
                    tb.HasAnnotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd");
                    tb.HasAnnotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");
                });
            });

            modelBuilder.Entity("IsoDocs.Domain.Cases.CaseAction", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTimeOffset>("ActionAt").HasColumnType("datetimeoffset");
                b.Property<int>("ActionType").HasColumnType("int");
                b.Property<Guid>("ActorUserId").HasColumnType("uniqueidentifier");
                b.Property<Guid>("CaseId").HasColumnType("uniqueidentifier");
                b.Property<Guid?>("CaseNodeId").HasColumnType("uniqueidentifier");
                b.Property<string>("Comment").HasColumnType("nvarchar(max)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<string>("PayloadJson").HasColumnType("nvarchar(max)");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.HasKey("Id");
                b.HasIndex("ActionType");
                b.HasIndex("ActorUserId");
                b.HasIndex("CaseNodeId");
                b.HasIndex("CaseId", "ActionAt");
                b.ToTable("CaseActions", (string)null);
            });

            modelBuilder.Entity("IsoDocs.Domain.Cases.CaseField", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid>("CaseId").HasColumnType("uniqueidentifier");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<string>("FieldCode").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                b.Property<Guid>("FieldDefinitionId").HasColumnType("uniqueidentifier");
                b.Property<int>("FieldVersion").HasColumnType("int");
                b.Property<DateTime>("PeriodEnd").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodEndColumn", true);
                b.Property<DateTime>("PeriodStart").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodStartColumn", true);
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.Property<string>("ValueJson").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("FieldDefinitionId");
                b.HasIndex("CaseId", "FieldCode").IsUnique();
                b.ToTable("CaseFields", (string)null, tb =>
                {
                    tb.HasAnnotation("SqlServer:IsTemporal", true);
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableName", "CaseFieldsHistory");
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableSchema", null);
                    tb.HasAnnotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd");
                    tb.HasAnnotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");
                });
            });

            modelBuilder.Entity("IsoDocs.Domain.Cases.CaseNode", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid?>("AssigneeUserId").HasColumnType("uniqueidentifier");
                b.Property<Guid>("CaseId").HasColumnType("uniqueidentifier");
                b.Property<DateTimeOffset?>("CompletedAt").HasColumnType("datetimeoffset");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<DateTimeOffset?>("ModifiedExpectedAt").HasColumnType("datetimeoffset");
                b.Property<string>("NodeName").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                b.Property<int>("NodeOrder").HasColumnType("int");
                b.Property<DateTimeOffset?>("OriginalExpectedAt").HasColumnType("datetimeoffset");
                b.Property<DateTime>("PeriodEnd").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodEndColumn", true);
                b.Property<DateTime>("PeriodStart").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodStartColumn", true);
                b.Property<DateTimeOffset?>("StartedAt").HasColumnType("datetimeoffset");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.Property<Guid>("WorkflowNodeId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("Status");
                b.HasIndex("WorkflowNodeId");
                b.HasIndex("AssigneeUserId", "Status");
                b.HasIndex("CaseId", "NodeOrder");
                b.ToTable("CaseNodes", (string)null, tb =>
                {
                    tb.HasAnnotation("SqlServer:IsTemporal", true);
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableName", "CaseNodesHistory");
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableSchema", null);
                    tb.HasAnnotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd");
                    tb.HasAnnotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");
                });
            });

            modelBuilder.Entity("IsoDocs.Domain.Cases.CaseRelation", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid>("ChildCaseId").HasColumnType("uniqueidentifier");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<Guid>("CreatedByUserId").HasColumnType("uniqueidentifier");
                b.Property<Guid>("ParentCaseId").HasColumnType("uniqueidentifier");
                b.Property<int>("RelationType").HasColumnType("int");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.HasKey("Id");
                b.HasIndex("ChildCaseId");
                b.HasIndex("ParentCaseId", "ChildCaseId", "RelationType").IsUnique();
                b.ToTable("CaseRelations", (string)null);
            });

            modelBuilder.Entity("IsoDocs.Domain.Communications.Comment", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid>("AuthorUserId").HasColumnType("uniqueidentifier");
                b.Property<string>("Body").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<Guid>("CaseId").HasColumnType("uniqueidentifier");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<bool>("IsDeleted").HasColumnType("bit");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.HasKey("Id");
                b.HasIndex("AuthorUserId");
                b.HasIndex("IsDeleted");
                b.HasIndex("CaseId", "CreatedAt");
                b.ToTable("Comments", (string)null);
            });

            modelBuilder.Entity("IsoDocs.Domain.Communications.Notification", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("Body").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<Guid?>("CaseId").HasColumnType("uniqueidentifier");
                b.Property<int>("Channel").HasColumnType("int");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<bool>("IsRead").HasColumnType("bit");
                b.Property<string>("LastError").HasColumnType("nvarchar(max)");
                b.Property<string>("PayloadJson").HasColumnType("nvarchar(max)");
                b.Property<DateTimeOffset?>("ReadAt").HasColumnType("datetimeoffset");
                b.Property<Guid>("RecipientUserId").HasColumnType("uniqueidentifier");
                b.Property<int>("RetryCount").HasColumnType("int");
                b.Property<DateTimeOffset?>("SentAt").HasColumnType("datetimeoffset");
                b.Property<string>("Subject").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<int>("Type").HasColumnType("int");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.HasKey("Id");
                b.HasIndex("CaseId");
                b.HasIndex("SentAt");
                b.HasIndex("RecipientUserId", "IsRead");
                b.ToTable("Notifications", (string)null);
            });

            modelBuilder.Entity("IsoDocs.Domain.Customers.Customer", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("Code").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                b.Property<string>("ContactEmail").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("ContactPerson").HasMaxLength(128).HasColumnType("nvarchar(128)");
                b.Property<string>("ContactPhone").HasMaxLength(64).HasColumnType("nvarchar(64)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("Note").HasMaxLength(1024).HasColumnType("nvarchar(1024)");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.HasKey("Id");
                b.HasIndex("Code").IsUnique();
                b.HasIndex("IsActive");
                b.HasIndex("Name");
                b.ToTable("Customers", (string)null);
            });

            modelBuilder.Entity("IsoDocs.Domain.Identity.Delegation", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<Guid>("DelegateUserId").HasColumnType("uniqueidentifier");
                b.Property<Guid>("DelegatorUserId").HasColumnType("uniqueidentifier");
                b.Property<DateTimeOffset>("EndAt").HasColumnType("datetimeoffset");
                b.Property<bool>("IsRevoked").HasColumnType("bit");
                b.Property<string>("Note").HasMaxLength(512).HasColumnType("nvarchar(512)");
                b.Property<DateTimeOffset>("StartAt").HasColumnType("datetimeoffset");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.HasKey("Id");
                b.HasIndex("DelegateUserId");
                b.HasIndex("IsRevoked");
                b.HasIndex("DelegatorUserId", "StartAt", "EndAt");
                b.ToTable("Delegations", (string)null);
            });

            modelBuilder.Entity("IsoDocs.Domain.Identity.Role", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<string>("Description").HasMaxLength(512).HasColumnType("nvarchar(512)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<bool>("IsSystemRole").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                b.Property<string>("PermissionsJson").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("PeriodEnd").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodEndColumn", true);
                b.Property<DateTime>("PeriodStart").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodStartColumn", true);
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.HasKey("Id");
                b.HasIndex("Name").IsUnique();
                b.ToTable("Roles", (string)null, tb =>
                {
                    tb.HasAnnotation("SqlServer:IsTemporal", true);
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableName", "RolesHistory");
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableSchema", null);
                    tb.HasAnnotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd");
                    tb.HasAnnotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");
                });
            });

            modelBuilder.Entity("IsoDocs.Domain.Identity.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("AzureAdObjectId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<string>("Department").HasMaxLength(128).HasColumnType("nvarchar(128)");
                b.Property<string>("DisplayName").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<bool>("IsSystemAdmin").HasColumnType("bit");
                b.Property<string>("JobTitle").HasMaxLength(128).HasColumnType("nvarchar(128)");
                b.Property<DateTime>("PeriodEnd").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodEndColumn", true);
                b.Property<DateTime>("PeriodStart").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodStartColumn", true);
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.HasKey("Id");
                b.HasIndex("AzureAdObjectId").IsUnique();
                b.HasIndex("Email").IsUnique();
                b.HasIndex("IsActive");
                b.ToTable("Users", (string)null, tb =>
                {
                    tb.HasAnnotation("SqlServer:IsTemporal", true);
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableName", "UsersHistory");
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableSchema", null);
                    tb.HasAnnotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd");
                    tb.HasAnnotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");
                });
            });

            modelBuilder.Entity("IsoDocs.Domain.Identity.UserRole", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid?>("AssignedByUserId").HasColumnType("uniqueidentifier");
                b.Property<DateTimeOffset>("AssignedAt").HasColumnType("datetimeoffset");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<DateTimeOffset>("EffectiveFrom").HasColumnType("datetimeoffset");
                b.Property<DateTimeOffset?>("EffectiveTo").HasColumnType("datetimeoffset");
                b.Property<Guid>("RoleId").HasColumnType("uniqueidentifier");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("RoleId");
                b.HasIndex("UserId", "EffectiveFrom", "EffectiveTo");
                b.HasIndex("UserId", "RoleId");
                b.ToTable("UserRoles", (string)null);
            });

            modelBuilder.Entity("IsoDocs.Domain.Workflows.DocumentType", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("Code").IsRequired().HasMaxLength(16).HasColumnType("nvarchar(16)");
                b.Property<string>("CompanyCode").IsRequired().HasMaxLength(16).HasColumnType("nvarchar(16)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<int>("CurrentSequence").HasColumnType("int");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                b.Property<DateTime>("PeriodEnd").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodEndColumn", true);
                b.Property<DateTime>("PeriodStart").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodStartColumn", true);
                b.Property<byte[]>("RowVersion").IsConcurrencyToken().IsRequired().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
                b.Property<int>("SequenceYear").HasColumnType("int");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.HasKey("Id");
                b.HasIndex("IsActive");
                b.HasIndex("CompanyCode", "Code").IsUnique();
                b.ToTable("DocumentTypes", (string)null, tb =>
                {
                    tb.HasAnnotation("SqlServer:IsTemporal", true);
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableName", "DocumentTypesHistory");
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableSchema", null);
                    tb.HasAnnotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd");
                    tb.HasAnnotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");
                });
            });

            modelBuilder.Entity("IsoDocs.Domain.Workflows.FieldDefinition", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("Code").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<bool>("IsRequired").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                b.Property<string>("OptionsJson").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("PeriodEnd").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodEndColumn", true);
                b.Property<DateTime>("PeriodStart").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodStartColumn", true);
                b.Property<int>("Type").HasColumnType("int");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.Property<string>("ValidationJson").HasColumnType("nvarchar(max)");
                b.Property<int>("Version").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("IsActive");
                b.HasIndex("Code", "Version").IsUnique();
                b.ToTable("FieldDefinitions", (string)null, tb =>
                {
                    tb.HasAnnotation("SqlServer:IsTemporal", true);
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableName", "FieldDefinitionsHistory");
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableSchema", null);
                    tb.HasAnnotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd");
                    tb.HasAnnotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");
                });
            });

            modelBuilder.Entity("IsoDocs.Domain.Workflows.WorkflowNode", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("ConfigJson").HasColumnType("nvarchar(max)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<string>("Name").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                b.Property<int>("NodeOrder").HasColumnType("int");
                b.Property<int>("NodeType").HasColumnType("int");
                b.Property<Guid?>("RequiredRoleId").HasColumnType("uniqueidentifier");
                b.Property<int>("TemplateVersion").HasColumnType("int");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.Property<Guid>("WorkflowTemplateId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("WorkflowTemplateId", "TemplateVersion", "NodeOrder").IsUnique();
                b.ToTable("WorkflowNodes", (string)null);
            });

            modelBuilder.Entity("IsoDocs.Domain.Workflows.WorkflowTemplate", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("Code").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<Guid>("CreatedByUserId").HasColumnType("uniqueidentifier");
                b.Property<string>("DefinitionJson").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Description").HasMaxLength(1024).HasColumnType("nvarchar(1024)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                b.Property<DateTime>("PeriodEnd").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodEndColumn", true);
                b.Property<DateTime>("PeriodStart").ValueGeneratedOnAddOrUpdate().HasColumnType("datetime2").HasAnnotation("SqlServer:TemporalIsPeriodStartColumn", true);
                b.Property<DateTimeOffset?>("PublishedAt").HasColumnType("datetimeoffset");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("datetimeoffset");
                b.Property<int>("Version").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("IsActive");
                b.HasIndex("Code", "Version").IsUnique();
                b.ToTable("WorkflowTemplates", (string)null, tb =>
                {
                    tb.HasAnnotation("SqlServer:IsTemporal", true);
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableName", "WorkflowTemplatesHistory");
                    tb.HasAnnotation("SqlServer:TemporalHistoryTableSchema", null);
                    tb.HasAnnotation("SqlServer:TemporalPeriodEndColumnName", "PeriodEnd");
                    tb.HasAnnotation("SqlServer:TemporalPeriodStartColumnName", "PeriodStart");
                });
            });

            // Relationships
            modelBuilder.Entity("IsoDocs.Domain.Attachments.Attachment", b =>
            {
                b.HasOne("IsoDocs.Domain.Cases.Case", null).WithMany().HasForeignKey("CaseId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("IsoDocs.Domain.Identity.User", null).WithMany().HasForeignKey("UploadedByUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("IsoDocs.Domain.Audit.AuditTrail", b =>
            {
                b.HasOne("IsoDocs.Domain.Identity.User", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.SetNull);
            });

            modelBuilder.Entity("IsoDocs.Domain.Cases.Case", b =>
            {
                b.HasOne("IsoDocs.Domain.Customers.Customer", null).WithMany().HasForeignKey("CustomerId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("IsoDocs.Domain.Workflows.DocumentType", null).WithMany().HasForeignKey("DocumentTypeId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("IsoDocs.Domain.Identity.User", null).WithMany().HasForeignKey("InitiatedByUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("IsoDocs.Domain.Workflows.WorkflowTemplate", null).WithMany().HasForeignKey("WorkflowTemplateId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("IsoDocs.Domain.Cases.CaseAction", b =>
            {
                b.HasOne("IsoDocs.Domain.Cases.CaseNode", null).WithMany().HasForeignKey("CaseNodeId").OnDelete(DeleteBehavior.NoAction);
                b.HasOne("IsoDocs.Domain.Cases.Case", null).WithMany().HasForeignKey("CaseId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("IsoDocs.Domain.Identity.User", null).WithMany().HasForeignKey("ActorUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("IsoDocs.Domain.Cases.CaseField", b =>
            {
                b.HasOne("IsoDocs.Domain.Cases.Case", null).WithMany().HasForeignKey("CaseId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("IsoDocs.Domain.Workflows.FieldDefinition", null).WithMany().HasForeignKey("FieldDefinitionId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("IsoDocs.Domain.Cases.CaseNode", b =>
            {
                b.HasOne("IsoDocs.Domain.Cases.Case", null).WithMany().HasForeignKey("CaseId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("IsoDocs.Domain.Identity.User", null).WithMany().HasForeignKey("AssigneeUserId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("IsoDocs.Domain.Workflows.WorkflowNode", null).WithMany().HasForeignKey("WorkflowNodeId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("IsoDocs.Domain.Cases.CaseRelation", b =>
            {
                b.HasOne("IsoDocs.Domain.Cases.Case", null).WithMany().HasForeignKey("ChildCaseId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("IsoDocs.Domain.Cases.Case", null).WithMany().HasForeignKey("ParentCaseId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("IsoDocs.Domain.Communications.Comment", b =>
            {
                b.HasOne("IsoDocs.Domain.Cases.Case", null).WithMany().HasForeignKey("CaseId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("IsoDocs.Domain.Identity.User", null).WithMany().HasForeignKey("AuthorUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("IsoDocs.Domain.Communications.Notification", b =>
            {
                b.HasOne("IsoDocs.Domain.Cases.Case", null).WithMany().HasForeignKey("CaseId").OnDelete(DeleteBehavior.SetNull);
                b.HasOne("IsoDocs.Domain.Identity.User", null).WithMany().HasForeignKey("RecipientUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("IsoDocs.Domain.Identity.Delegation", b =>
            {
                b.HasOne("IsoDocs.Domain.Identity.User", null).WithMany().HasForeignKey("DelegateUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("IsoDocs.Domain.Identity.User", null).WithMany().HasForeignKey("DelegatorUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("IsoDocs.Domain.Identity.UserRole", b =>
            {
                b.HasOne("IsoDocs.Domain.Identity.Role", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("IsoDocs.Domain.Identity.User", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("IsoDocs.Domain.Workflows.WorkflowNode", b =>
            {
                b.HasOne("IsoDocs.Domain.Workflows.WorkflowTemplate", null).WithMany().HasForeignKey("WorkflowTemplateId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
